### ISSUE TITLE
No Run/Debug/Inspect buttons

### ISSUE THREAD

**Issue by Northimus** [sakamoto66/vscode-playwright-test-runner#12]
Hi. For some reason I don't see run/debug/inspect buttons, why can this be happening? 
![image](https://user-images.githubusercontent.com/100562706/155952331-e2d75ef4-6e93-46ba-ba5c-1c514d0e27e5.png)

**Comment by sakamoto66** [comment]
Hi,
What is the file name?
run/debug/inspect buttons is displayed when the file name is **/*.{test,spec}.{js,jsx,ts,tsx}.

![image](https://user-images.githubusercontent.com/2166547/155968411-0bb21665-c3a6-4db8-b376-192b97ed254e.png)

https://github.com/sakamoto66/vscode-playwright-test-runner#extension-settings-for-common

**Comment by Northimus** [comment]
Thank you, that was it :)
