### ISSUE TITLE
Escape equals sign in env variable when

### ISSUE THREAD

**Issue by sramshettyMerit** [sakamoto66/vscode-playwright-test-runner#17]
How can i escape equals sign in env variable when I add it to  settings --> user --> Playwright Environment Variables.
For example when I add
ENV_VAR1=kGN1b7UrPpjp6Zk37jE-_HRf3ma+ARxuN9nBx55pqVwCdXGOXjvJ=qDSgQ9W=g26
and try to access **process.env.ENV_VAR1** I get the value as **kGN1b7UrPpjp6Zk37jE-_HRf3ma+ARxuN9nBx55pqVwCdXGOXjvJ**. It strips off the value **=qDSgQ9W=g26**

I tried escaping by putting in quotes, ^ and \ but still cannot read the entire value
ENV_VAR1="kGN1b7UrPpjp6Zk37jE-_HRf3ma+ARxuN9nBx55pqVwCdXGOXjvJ=qDSgQ9W=g26"
ENV_VAR1=kGN1b7UrPpjp6Zk37jE-_HRf3ma+ARxuN9nBx55pqVwCdXGOXjvJ^=qDSgQ9W^=g26
ENV_VAR1=kGN1b7UrPpjp6Zk37jE-_HRf3ma+ARxuN9nBx55pqVwCdXGOXjvJ\=qDSgQ9W\=g26

**Comment by sakamoto66** [comment]
Hi
This was a bug.
I have released a fix. v1.4.1
Set your environment variables like this:
```
ENV_VAR1=kGN1b7UrPpjp6Zk37jE-_HRf3ma+ARxuN9nBx55pqVwCdXGOXjvJ=qDSgQ9W=g26
```

**Comment by sramshettyMerit** [comment]
> Hi This was a bug. I have released a fix. v1.4.1 Set your environment variables like this:
> 
> ```
> ENV_VAR1=kGN1b7UrPpjp6Zk37jE-_HRf3ma+ARxuN9nBx55pqVwCdXGOXjvJ=qDSgQ9W=g26
> ```

Thank you!
